### ISSUE TITLE
Documentation about block content type

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#127]
Block is a very important feature of the templates and should be an own section in http://docs.sulu.io/en/latest/book/creating-a-basic-website/adding-a-template.html site.
Currently its complete missing.

**Comment by wachterjohannes** [comment]
Additionally add block as content type references (minimum link to longer description)

**Comment by alexander-schranz** [comment]
seems tobe documented know in http://docs.sulu.io/en/latest/book/templates.html#content-blocks
