### ISSUE TITLE
Missing parameters in docs for sulu_categories

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#223]

**Comment by chirimoya** [comment]
Missing parameter documentation. (`$locale`, `$parent = null`)

http://docs.sulu.io/en/latest/reference/twig-extensions/functions/sulu_categories.html
https://github.com/sulu/sulu/blob/e074d5b546ae1b6b7411d9891e92e95cdc3abb96/src/Sulu/Bundle/CategoryBundle/Twig/CategoryTwigExtension.php#L78
