### ISSUE TITLE
When adding a theme Bundle should be specified

### ISSUE THREAD

**Issue by piratadelfuturo** [sulu/sulu-docs#227]
In the documentation says that the theme can just be added (https://github.com/sulu/sulu-docs/blob/develop/book/creating-a-basic-website/adding-a-theme.rst#L25-L36), but it should be added inside the ClientWebsiteBundle folder, other wise seems it looks on the default folder and not in the new template.

[1/5] InvalidArgumentException: The file "views/templates/complex.html.twig" does not exist (in: /var/www/pmg/pmg_social/app/Resources/themes/default, /var/www/pmg/pmg_social/app/Resources).

**Comment by piratadelfuturo** [comment]
OK my mistake.
To use a theme it SHOULD be specified in the webspace:
    <theme>
        <key>MY_THEME</key>

**Comment by wachterjohannes** [comment]
so it can be closed?
