### ISSUE TITLE
Commands not executable after running composer create-project

### ISSUE THREAD

**Issue by gisostallenberg** [sulu/sulu-docs#265]
In **Getting Started** `composer create-project` is mentioned as the command to start a project, but after running that the commands `bin/adminconsole` and `bin/adminconsole` mentioned later on that page are not executable.

As mentioned in https://github.com/composer/composer/issues/5622, the command should be executed as

``` bash
composer create-project sulu/sulu-minimal my-project --no-interaction --prefer-source
```

which is really slow by the way.

**Comment by danrot** [comment]
Yeah, it's slow, and I don't know if you really want to do that in production... It basically means that all the git stuff is also downloaded, which eats up disk space for no reason. We should probably add to the documentation that these files must be made executable...

**Comment by gisostallenberg** [comment]
I will create a PR for that.

**Comment by danrot** [comment]
@gisostallenberg Have you already created that PR?

**Comment by danrot** [comment]
@gisostallenberg How did you install it? Just tried to reproduce it, to make the docs PR on my own, but after executing one of the following commands the permissions were already set correctly:

```bash
composer create-project sulu/sulu-minimal
composer create-project sulu/sulu-minimal --prefer-dist
```

**Comment by alexander-schranz** [comment]
@danrot In the symfony documentation they always write `php bin/console` so it works to 100%. Maybe we should do the same in our documentation. On windows you need to write `php bin/console` when not using a bash emulation.

**Comment by danrot** [comment]
@gisostallenberg Are you using Windows? Can you test and see if what @alexander-schranz has suggested works?

**Comment by gisostallenberg** [comment]
This issue is stale
