### ISSUE TITLE
sulu.rlp.part can be used multiple times

### ISSUE THREAD

**Issue by baroso** [sulu/sulu-docs#272]
Can you add a description in the docs ...
http://docs.sulu.io/en/latest/reference/content-types/resource_locator.html
... that sulu.rlp.part can be used multiple times and the field values will be concatenated!?

Thanks!

**Comment by danrot** [comment]
Feel free to contribute :-) It's in this file: https://github.com/sulu/sulu-docs/blob/72727902beb4f1f7f8c04490ecc9b8722fad33d0/reference/content-types/resource_locator.rst

**Comment by baroso** [comment]
@danrot 
No problem, I've forked this rep already.
Should I wait with my documentation until the following Bug is resolved?

https://github.com/sulu/sulu/issues/2587

**Comment by danrot** [comment]
@baroso No, that doesn't matter, and probably won't be fixed that soon... actually, the documentation already refers to `Fields`, which is a subtle hint 😀
