### ISSUE TITLE
Wrong Custom error page Documentation

### ISSUE THREAD

**Issue by michlor** [sulu/sulu-docs#289]
Wrong closing Tag at http://docs.sulu.io/en/latest/cookbook/custom-error-page.html

`<template type="error">ClientWebsiteBundle:views:error.html.twig</error-template>`

**Comment by danrot** [comment]
Thank you, fixed in 53f6bdb687f28ee973565ccd2e0d312e9da76b21.

Feel free to create a PR for small changes like this :-)
