### ISSUE TITLE
Add documentation for add new webspace locale

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#299]
Its not documented that you have to run `sulu:document:initialize` when add a new locale to there webspace.  Also after doing that he need to add the permission for this locale to his user.

Dont know where we should add this documentation.

Some issues:

https://github.com/sulu/sulu/issues/3143
https://github.com/sulu/sulu-standard/issues/709

**Comment by RichardFrontwise** [comment]
+1.
Maybe a good improvement to automatically give the admin user permission on the new locale?

**Comment by alexander-schranz** [comment]
@RichardFrontwise thx for the links for the permissions you should create an issue in https://github.com/sulu/sulu/issues if there does none exist.

**Comment by danrot** [comment]
Please don't create an issue for that, we've already discussed that, and we don't want any user to automatically gain any permissions. That's just a high security risk, since developers might not realize it, and loads of people have permissions they shouldn't have.
