### ISSUE TITLE
Reference/DocumentManager/DataFixtures DataFixtures not published

### ISSUE THREAD

**Issue by oafx** [sulu/sulu-docs#306]
Hi,

not sure if this is intended behavior and i'm new to sulu so i don't know if i'm doing it right but while the DataFixtures example is setting the WorkflowStage to published, the created pages seem only to be really published after i call ```$documentManager->publish()``` for them. Maybe include this somehow in the docs?

Greetings
Chris

**Comment by danrot** [comment]
@oafx What `DataFixture` example are you talking about?

**Comment by alexander-schranz** [comment]
@oafx I think you mean this example: http://docs.sulu.io/en/latest/reference/components/document-manager/fixtures.html
With the **drafting** feature I think you need to load the fixtures into both workspaces:

```bash
php app/adminconsole sulu:document:fixtures:load
# and
php app/websiteconsole sulu:document:fixtures:load
```

@danrot is this missing documentation or should the behaviour of the fixtures load be changed?

**Comment by oafx** [comment]
@danrot @alexander-schranz yes, i was reffering to that one.. 

i didn't even realize that there was a difference between executing those commands on different consoles.. sorry

**Comment by alexander-schranz** [comment]
@oafx the admin and the website has different PHPCR workspaces if you publish a page it is copied from Admin to Website workspace. So I think the fixtures running only on admin will only add them to the admin phpcr workspace as we added drafting with 1.3 the fixtures need I think included in both workspaces.

Did run both command fix your problem?

**Comment by oafx** [comment]
@alexander-schranz well actually i'm using sulu-standard instead of minimal and since those consoles aren't included in that package i figured i simply had to use the symfony `app/console` (maybe i didn't read enough, sorry again, but) which is also being suggested to use in the fixture docs page `$ php app/console sulu:document:fixtures:load`

well and that again led me to use the `$documentManager->publish()` to fix my problem. Just wanted to note that the described way in the documentation didn't work as expected for me.

**Comment by alexander-schranz** [comment]
@oafx on sulu standard it calls `app/console` and `app/webconsole`.

**Comment by oafx** [comment]
@alexander-schranz which means it should work out of the box?

**Comment by danrot** [comment]
I would say calling `publish` in the fixture is the better solution, since we already talked about doing some optimizations in the live workspace. Then you shouldn't just import the same data in both workspaces, but let the document manager handle that instead. @oafx A PR would be very appreciated :-)

**Comment by oafx** [comment]
@danrot done. is this sufficient?
