### ISSUE TITLE
Smart content provider missing set entity repository class in orm.xml

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#322]
We should add a note or something to the http://docs.sulu.io/en/1.5/cookbook/smart-content-data-provider.html#service-definition that the Repository Class also need to be set on the entity.orm.xml file because Doctrine ignores the class and use the class from the .orm.xml file when not set its still EntityRepository.

**Comment by danrot** [comment]
Actually it should be using the repository service being created by the `PersistenceBundle`, shouldn't it?

In addition to that we could create a note, that says you can also use your own repository, but that it has to be configured to be used in doctrine configuration then.

**Comment by wachterjohannes** [comment]
@danrot external developers may not use the `PersistenceBundle` for custom modules. so I would go with this configuration (and add the `respository-class` to the `orm.xml`). Maybe we could add a link here that the `PersistenceBundle` would be a good addition at this point.

**Comment by danrot** [comment]
Well, I think there speaks nothing against using it in external bundles, but you are right, they don't have to...
