### ISSUE TITLE
Missing details about adding a default theme to a webspace.xml

### ISSUE THREAD

**Issue by Rowanism** [sulu/sulu-docs#360]
The ["Adding a theme"](http://docs.sulu.io/en/latest/book/themes.html) documentation tells you the following:
> This will configure a default theme which can be enabled in the app/Resources/webspaces/<webspace>.xml file by adding:
> `<theme>default</theme>`

It does not specify the exact location (between `localizations` and `default-templates`).
Pasting the tag anywhere else in the xml results in Symfony throwing an exception:

> XmlParsingException
> [ERROR 1871] Element '{http://schemas.sulu.io/webspace/webspace}theme': This element is not expected. 

So this can heavily confuse people.

**Comment by alexander-schranz** [comment]
Hello @Rowanism,

thank you for your issue. I think we will this fix in the Webspace XSD file that this it is not longer required to be at a specific position. sulu/sulu#3764

**Comment by alexander-schranz** [comment]
This should not longer be the case for `1.6.15`

**Comment by wachterjohannes** [comment]
@alexander-schranz i think we can close this? what do you think?

**Comment by danrot** [comment]
We definitely can, so I do it :smile:
