### ISSUE TITLE
Can't figure out how pages are added to a webspace

### ISSUE THREAD

**Issue by TomSchillemans** [sulu/sulu-docs#386]
We have a webspace and I try to make a page template
This template has everything it needs including a twig template.
Though, I don't see the template in the admin pull down.
And I can't figure out how I can add a template to a webspace

**Comment by alexander-schranz** [comment]
Hello @TomSchillemans,

1. did you cleared the admin cache?
2. is `<key>` the same name as the filename?
3. is `<template>` correctly? attention: template definition is without file extension
4. exists template the template as `.html.twig`? attention .html is required

to help you better show your template code and paths where you created the files.

Easiest way to create a new template:

 - copy `default.xml` to e.g. `new.xml`
 - change the `<key>` from `default` to `new`
 - change the `<template>` from `templates/default` to `templates/new`
 - create the `new.html.twig`
 - clear the cache `rm -r var/cache/*`

**Comment by TomSchillemans** [comment]
A admin cache clear worked. I basically have to cache clear every time I make a template and everytime I delete one. Its not too big a problem, just something we have to keep in mind here.

I have another thing but I'll make a new ticket for that as soon as I figure out if I am not missing something.
