### ISSUE TITLE
Running sulu on https

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/sulu-docs#470]
Lately some community members had problems setting up sulu on https.

Sulu itself doesn't care about the protocol. Mostly its an issue of a false definition of trusted proxies which is used by symfony to detect the current protocol.

See https://symfony.com/doc/current/deployment/proxies.html

But it seems like we should maybe document how to debug the headers e.g.:

Symfony depends the protocol on the output of the following function

```php
$request->isSecure(); // Need to be true
```

If that return false it can have 2 reasons:

**1. There exist a proxy and the application is not configured to trust the proxies headers**

Set trusted proxies IPs can be done in the `.env` file or in the index.php see documentation above.

It can debug this with:

```php
$request->isFromTrustedProxy(); // this should be true
$request->getTrustedValues(self::HEADER_X_FORWARDED_PROTO); // returns 'https', 'on', 'ssl' or '1'
```

**2. There is no proxy but $_SERVER['HTTPS'] is not set to on**

If you have no proxy you can force HTTPS by setting the server variable for https on in nginx you can do this in your vhost fastcgi_params with:

```nginx
        fastcgi_param HTTPS on;
```

Not sure what the equivalent is in Apache Webserver.

It can debug this with:

```php
$request->server->get('HTTPS'); // returns 'on', '1', ...
```

**Comment by nnatter** [comment]
I think this was fixed by #560. Fee free to reopen if it was not 🙂
