### ISSUE TITLE
Show how to render an image from teaser

### ISSUE THREAD

**Issue by terrluhr** [sulu/sulu-docs#473]
In teaser selection there is an example how to render a basic link. But I think it's Mir or less obvious how to do that. But I cannot find a way to render an image from the media Id

**Comment by alexander-schranz** [comment]
@terrluhr thank you for the issue I updated the docs using the [sulu_resolve_media](https://docs.sulu.io/en/2.0/reference/twig-extensions/functions/sulu_resolve_media.html#sulu-resolve-media) function to output the image.

**Comment by danrot** [comment]
Fixed in #474
