### ISSUE TITLE
Custom Entities with Admin

### ISSUE THREAD

**Issue by Warxcell** [sulu/sulu-docs#496]
Couldn't find a documenation how to create custom entities with some standart admin in sulu.

**Comment by alexander-schranz** [comment]
Documentation how to get custom entities into the Sulu UI can be found here: https://docs.sulu.io/en/2.0/book/extend-admin.html

I really can recommend todo the workshop assignements: https://github.com/sulu/sulu-workshop-symfony-live-berlin-2019
