### ISSUE TITLE
Add numeric content type

### ISSUE THREAD

**Issue by manuxi** [sulu/sulu-docs#521]
# Problem description

I'd like to give the content manager the posibility to add e.g. a price which I'd like to format in the template. It could also be possible to use numerics for other tasks (e.g. range slider). At the moment only a text_line can be used for those tasks. If there is a posibility to enter stuff wrong, someone will do.

# Proposed solution

Add an integer content type
Add an float content type

**Comment by danrot** [comment]
Fixed in #522
