### ISSUE TITLE
Some documentation feedback

### ISSUE THREAD

**Issue by dbu** [sulu/sulu-docs#587]
I have been working through version 2.2 of the documentation. It is good reading, you did a great job!

I have a couple of details that i noticed that could be improved.

* note in section https://docs.sulu.io/en/2.2/book/templates.html#language-independent-properties should probably have a bit less technical detail and instead link to a cookbook entry or something that explains how to do that migration
*  https://docs.sulu.io/en/2.2/book/webspaces.html#resource-locator-optional had me confused a bit. it says "influences the design of the URLs for the content" - i'd say "the resource path is part of the URLs for the content". influence is very vague, and it is not the design of URLs but rather a part of it. @chirimoya told me that there is a thing in place that creates redirect urls when renaming so that old bookmarks / links from external sites don't lead to 404. that could be mentioned here as well (and linked to some place if there is a place with more information on the subject)
* did the "book" get reorganized at some point? the last paragraph in https://docs.sulu.io/en/2.2/book/webspaces.html talks about next creating a template for a page, but that chapter is before the webspace chapter.

**Comment by nnatter** [comment]
Hey,
thanks a lot for your feedback - we are really appreciating this!
I added a PR to change some things you mentioned here: #603
